files: >
  (?x)^(
    src/*|
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: ["--maxkb=2048"]

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args: ["--line-length=79", "--skip-string-normalization"]

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile=black", "--line-length=79"]

  - repo: https://gitlab.com/PyCQA/flake8
    rev:  3.9.2
    hooks:
      - id: flake8
        args: [
          "--max-line=79",
          "--docstring-convention=google",
          "--ignore=D100,D104,D105,D415,E203,W503",
          "--per-file-ignores=tests/*:D100,D101,D102,D104,D106,D107,D205",
          "--ignore-decorators=property",
        ]
        additional_dependencies: [
          flake8-docstrings,
          flake8-pytest-style
        ]

  - repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
      - id: interrogate
        args: [
          "-vv",
          "--ignore-module",
          "--ignore-magic",
          "--ignore-setters",
          "--ignore-private",
          "--ignore-semiprivate",
          "--fail-under=80",
        ]
        exclude: ^(tests)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args:
          - --ignore-missing-imports
          - --allow-untyped-decorators
          - --follow-imports=skip

  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.8.1
    hooks:
      - id: pylint
        types: [ python ]
        args: ["--max-line-length=79", "--errors-only", "--disable=E0401"]
